#ifndef COMMON_H
#define COMMON_H

#define FS_MAGIC 0x12345678

#define BLOCK_SIZE 4096
#define MAXIMUM_BLOCKS 64
#define DISK_SIZE (BLOCK_SIZE * MAXIMUM_BLOCKS)

#define ROOT_INODE 0

#define INODE_BITMAP_SIZE ((MAXIMUM_INODES + 7) / 8)
#define DATA_BITMAP_SIZE ((MAXIMUM_DATA_BLOCKS + 7) / 8)

#define INODE_SIZE 256
#define INODES_PER_BLOCK (BLOCK_SIZE / INODE_SIZE)
#define MAXIMUM_INODE_BLOCKS 5
#define MAXIMUM_INODES (MAXIMUM_INODE_BLOCKS * INODES_PER_BLOCK)
#define INODE_DIRECT_POINTERS_COUNT 12

#define MAXIMUM_DATA_BLOCKS (MAXIMUM_BLOCKS - DATA_BLOCK_START)

#define SUPERBLOCK_BLOCK 0
#define INODE_BITMAP_BLOCK 1
#define DATA_BITMAP_BLOCK 2
#define INODE_TABLE_BLOCK_START 3
#define DATA_BLOCK_START 8

#define FS_SUCCESS 0
#define FS_ERROR -1

#endif